### PR TITLE
Samplingfeaturedataset dev

### PR DESCRIPTION
**Pull request by Elijahwalkerwest**
Added eager loading for samplingfeaturedataset to try and cut down on query time.

### CODE REVIEW

**Comment by emiliom** [comment]
@lsetiawan: I'll let you review this PR; I'm too tied up today, then gone.

I see that it's a PR on the dev branch, so it won't impact the new release (and won't go into the new release, to be issued today).

**Comment by emiliom** [comment]
I'm ready to go with the release (it's in draft form right now). @lsetiawan, do you think you'll have time to review and merge into master this PR? I have a couple more NicaDIF things for you :|

**Comment by lsetiawan** [comment]
@Elijahwalkerwest I noticed that you are not meeting a lot of Python PEP8 Rules, so I've made it more visible. I am doing this so no one has to go back and clean up again for Python Pep8 errors. So please fix your code to meet PEP8. You will see the errors here: https://travis-ci.org/ODM2/ODM2PythonAPI/jobs/331031358

**Comment by emiliom** [comment]
That's it. I'm releasing from master as is, w/o this PR. Sorry @Elijahwalkerwest!

**Comment by lsetiawan** [comment]
@ocefpaf Do you know why the Docs creation is failing here? Thanks!

```
Link check complete; look for any errors in the above output or in build/linkcheck/output.txt.
make: *** [linkcheck] Error 1
```

**Comment by ocefpaf** [comment]
> @ocefpaf Do you know why the Docs creation is failing here? Thanks!

@lsetiawan `linkcheck` navigates the links in the docs to ensure they are all working. The error `linkcheck` is pointing refers to the link https://www.nsf.gov/awardsearch/showAward?AWD_ID=1224638, which returned a [`503 Sever Error`](https://travis-ci.org/ODM2/ODM2PythonAPI/jobs/332046722#L1862) the time the docs ran.

I checked and the link seems to be OK now, so you can restart Travis-CI to ensure that or, if you know the context of that link in docs and a server error is not important, just merge it :wink:

**Comment by lsetiawan** [comment]
Thanks @ocefpaf. That makes sense, didn't know it's doing that. Cool! :D

**Comment by lsetiawan** [comment]
All is well now, and I have tested the changes. Merging... Thanks @Elijahwalkerwest

**Pull request merged**
