### PR TITLE
pip install with forked geoalchemy

### PR DESCRIPTION
**Pull request by ocefpaf**
@emiliom can you take a look and see if this does the trick for issue  #18?

(My pip tricks are aging as I move to conda...)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Ideally we would set a regression test up to check if this is using the right `geoalchemy`.

**Comment by emiliom** [comment]
Thank you, @ocefpaf!! I merged the pull request then tested the installation. Unfortunately, it didn't work. Here are my exact steps (on Ubuntu):

```bash
conda create -n odm2api_testga python=2.7 sqlalchemy shapely psycopg2 pymysql pyodbc
source activate odm2api_testga
pip install git+https://github.com/ODM2/ODM2PythonAPI.git
```
And the error message:
```
Collecting geoalchemy==0.7.3 (from odm2api==0.1)
  Could not find a version that satisfies the requirement geoalchemy==0.7.3 (from odm2api==0.1) (from versions: 0.1, 0.1.1, 0.2, 0.3, 0.3.1, 0.4, 0.4.1, 0.5, 0.6, 0.7, 0.7.1, 0.7.2)
No matching distribution found for geoalchemy==0.7.3 (from odm2api==0.1)
```
It looks to me like it's looking at `pypi`, not our github fork ... That's the problem we haven't been able to solve.

**Comment by ocefpaf** [comment]
My venv might have been "contaminated" by a previously installed
geoalchemy. I will take another look tomorrow.

**Comment by emiliom** [comment]
> My venv might have been "contaminated" by a previously installed geoalchemy

Strange. There shouldn't be any other geoalchemy 0.7.3 out there ... Now, `geoalchemy2` is an entirely different thing.

Thanks so much!!

**Comment by ocefpaf** [comment]
> Strange. There shouldn't be any other geoalchemy 0.7.3 out there 

I was installing `geoalchemy 0.7.3` using the "long git URL" to test.  That is how I contaminated the env.

I will make a few tests and get back to you, but if you want to use conda that will be much easier.

**Comment by emiliom** [comment]
Thanks!

> but if you want to use conda that will be much easier.

We do want to use conda with al this "ODM2" stuff, later on. Ideally soon, but we're just not ready, skills wise. And that's the other conversation I mentioned, but that's for offline emails ... I really should try to follow up with you very soon!

At the same time, we'd like to make sure odm2api is installable as is by people using pip install, w/o requiring conda.

**Comment by ocefpaf** [comment]
I completely forgot that you need to use `--process-dependency-links`  I tested it here on a clean env and it works.  The problem is that `dependency-links` seems to be deprecated!

(I got a deprecation warning. It seems that installing from packages from external sources with pip is getting harder ad harder.)

Also, my PR my not be ideal for those who want to install the requirements file.  I am sending a new one to fix it.

**Pull request merged**
