### PR TITLE
new badge

### PR DESCRIPTION
**Pull request by ocefpaf**
Change the AppVeyor badge to the one attached to the ODM2 org.
If everything works as expected anyone with access to the ODM2 org and an AppVeyor account will have Adim rights to the AppVeyor instance.

### CODE REVIEW

**Comment by emiliom** [comment]
AppVeyor failed here. I assume I should hold off on merging, then?

**Comment by ocefpaf** [comment]
> AppVeyor failed here. I assume I should hold off on merging, then?

Not really. AppVeyor was never green from day one.

**Comment by emiliom** [comment]
OK. I can't keep track.

Should I merge? I'm guessing so.

**Comment by ocefpaf** [comment]
It is OK to merge. Addressing those errors are not in our priority list b/c it would require some deep knowledge of databases on Windows.

**Pull request merged**
