### PR TITLE
use conda-forge

### PR DESCRIPTION
**Pull request by ocefpaf**
@lsetiawan and @emiliom this PR makes use of the conda-forge version of the odm2 packages.

### CODE REVIEW

**Comment by ocefpaf** [comment]
It looks like the AppVeyor failure here is unrelated to this PR.

**Comment by lsetiawan** [comment]
All of these PR should have been committed to the `development` branch, but oh well, it's done now. I'm gonna pull the latest stuff to `development`.

**Comment by ocefpaf** [comment]
> All of these PR should have been committed to the `development` branch, but oh well, it's done now. I'm gonna pull the latest stuff to `development`.

Sorry for the trouble. It is hard to revert to an exception workflow when working on many other OSS projects that adhere to the standard workflow. But I'll try to remember next time :grimacing: 

BTW, maybe the "use-development-branch-as-master" workflow should be documented in the README file to help people outside of the ODM2 circle contribute to the code here.

**Comment by lsetiawan** [comment]
> Sorry for the trouble.
No worries. I should've checked. 

> BTW, maybe the "use-development-branch-as-master" workflow should be documented in the README file to help people outside of the ODM2 circle contribute to the code here.

That's a great idea. Thanks. I'll add that in somewhere.

@ocefpaf The ODM2 Team has been following the [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

**Comment by ocefpaf** [comment]
> @ocefpaf The ODM2 Team has been following the Gitflow workflow.

Maybe you should just mention that in the README. It is not widely used and more people will trip on this.

**Comment by ocefpaf** [comment]
PS: http://endoflineblog.com/gitflow-considered-harmful :smile_cat:

**Comment by lsetiawan** [comment]
Thank you for the article. :smile: Very useful!

**Comment by horsburgh** [comment]
And also just one person's opinion. I disagree with the statement that it's not widely used, and so does your blogger (even though he clearly doesn't like it)!

**Comment by ocefpaf** [comment]
> And also just one person's opinion. 

Indeed. That blog was just an example I sent to @lsetiawan.

>  I disagree with the statement that it's not widely used

It was at the time of the original post and in the web community. Since then it became obscure and the vast majority of the OSS community dropped the gitflow.

However, it is important to note that the best workflow is the one you are used to :wink: 

ODM2 should only change from gitflow to another community standard if the group wants to reduce the learning curve for newcomers.

**Pull request merged**
