### PR TITLE
Fixqueries

### PR DESCRIPTION
**Pull request by sreeder**
fix issues :
#65 #66 and #67 
#48 is almost completed, I just need to figure out how to install geoalchemy-odm2 to the conda testing environment
Fix the create queries so they return the newly created object( and its id)

suggest version increment to 0.5.1

### CODE REVIEW

**Comment by sreeder** [comment]
@emiliom @ocefpaf  When I merge in this pull request how do I make a new release on the conda ODM2 channel?

**Comment by ocefpaf** [comment]
>  I make a new release on the conda ODM2 channel?

Just ping me and I will do it. Waiting for the new release.

**Comment by sreeder** [comment]
@ocefpaf the release has been made and we are ready for a new conda version. Thanks!

**Comment by ocefpaf** [comment]
Done in https://github.com/ODM2/conda-recipes-ODM2/pull/39

Thanks @sreeder!

**Comment by emiliom** [comment]
Thanks to both of you! This is great.

**Pull request merged**
