### PR TITLE
remove ODM1_1_1 related tests

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR removes the tests for the code removed in https://github.com/ODM2/ODM2PythonAPI/pull/81

There are now some other failures that may be real or due to our testing setup (I also suspect some unicode/decoding issues, not sure). 

@lsetiawan can you review this and take a look at the new failures?

### CODE REVIEW

**Comment by lsetiawan** [comment]
@ocefpaf Sorry I didn't see this! Must've gone past my radar. From the error:

```
ProgrammingError: (pymysql.err.ProgrammingError) (1146, u"Table 'odm2.samplingfeatures' doesn't exist")
```

This might be caused by the database instance not firing up.

**Comment by ocefpaf** [comment]
> @ocefpaf Sorry I didn't see this! Must've gone past my radar.

No problem.

> This might be caused by the database instance not firing up.

I guess it was broken for a while then and we did not notice.
Can you run the tests locally and let me know what is missing on Travis-CI?

(I have `0` experience with databases.)

**Comment by lsetiawan** [comment]
> Can you run the tests locally and let me know what is missing on Travis-CI?
> (I have 0 experience with databases.)

Yea. One sec. Lemme get this setup. I'll get back to you asap.

**Comment by lsetiawan** [comment]
@ocefpaf It seems like the mysql setup [script](https://github.com/ODM2/ODM2PythonAPI/blob/master/ci-helpers/mysql_setup.sh#L2) might requires sudo, and travis is not allowed to use sudo: https://travis-ci.org/ODM2/ODM2PythonAPI/jobs/263084731#L643

**Comment by ocefpaf** [comment]
I'll investigate the alternatives. Thanks @lsetiawan!

**Comment by lsetiawan** [comment]
When I tried using `sudo: required` the tests works and now the failures are actual API errors: https://travis-ci.org/lsetiawan/ODM2PythonAPI/jobs/264905665#L1559

**Comment by ocefpaf** [comment]
> When I tried using `sudo: required` the tests works and now the failures are actual API errors: https://travis-ci.org/lsetiawan/ODM2PythonAPI/jobs/264905665#L1559

Cool. I did that for now so we can focus on those errors.

I am also reading this https://docs.travis-ci.com/user/database-setup/

Maybe we can avoid `sudo` altogether.

**Comment by lsetiawan** [comment]
> I am also reading this https://docs.travis-ci.com/user/database-setup/

I saw that documentation too, but my question is can we stop and start the mysql server without sudo in travis?

**Comment by lsetiawan** [comment]
@ocefpaf the problem comes when we have to add a line of configuration for mysql-server https://github.com/ODM2/ODM2PythonAPI/blob/master/ci-helpers/mysql_setup.sh#L10. I will take a look if there's a way that this can be done through SQL rather than manually through script!

**Comment by ocefpaf** [comment]
Looks like the API change is that `createModel` now only takes `model` instead of `code`, `name`, and `description`. Did you make that change? What is `model` in the new context? One of those 2 or a new object?

> @ocefpaf the problem comes when we have to add a line of configuration for mysql-server https://github.com/ODM2/ODM2PythonAPI/blob/master/ci-helpers/mysql_setup.sh#L10. I will take a look if there's a way that this can be done through SQL rather than manually through script!

I'm reading more on that too but `sudo: required` is fine for now. I want to stop merging failing PRs to avoid regressions and API breakages without warning :wink:

**Comment by ocefpaf** [comment]
Thanks @lsetiawan!

**Comment by lsetiawan** [comment]
> Did you make that change? What is model in the new context? One of those 2 or a new object?
No. I didn't make the updates to the API, but I know how it works. `Model` is an ODM2API Model [Object](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/models.py#L708).

>  I want to stop merging failing PRs to avoid regressions and API breakages without warning
 Should I not merge yet then?

**Comment by ocefpaf** [comment]
> No. I didn't make the updates to the API, but I know how it works. `Model` is an ODM2API Model [Object](https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/models.py#L708).

Awesome! I would never find that b/c I don't really use `ODM2PythonAPI`. Is it an easy fix? Do you need my help with that?

> Should I not merge yet then?

Got for it. This is not a code change but a tool to fix the CI :smile:  My guess is that we are close to make it green again.

**Comment by ocefpaf** [comment]
BTW, my reasoning when made https://github.com/ODM2/ODM2PythonAPI/pull/90#issuecomment-322592137 I meant that  the test code change should've be part of the PR that implemented the API change. However, because Travis-CI has been broken for ages, we started ignoring it and accumulating changes without really knowing the consequences. Only local tests of the type "works for me."

**Comment by lsetiawan** [comment]
> Awesome! I would never find that b/c I don't really use ODM2PythonAPI. Is it an easy fix? Do you need my help with that?

Should be a fairly easy fix. I think I got it 😉 , thanks for offer. I'll make a PR once it's done.

**Pull request merged**
