### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by sreeder**
- remove  ODM1.1.1
- remove LikeODM1
- add missing return statements
- cleanup documentation in read_service

I am planning on creating a new odm2api release version:0.6.0 when this request is approved

### CODE REVIEW

**Comment by emiliom** [comment]
Just for reference: Issue #38 can be closed once this PR is merged.

I'm reviewing this PR now.

**Comment by emiliom** [comment]
Great to see these cleanups, thanks! 

Regarding issuing a new release: given that a release was issued just less than two weeks ago, how about we wait a little longer to give @ocefpaf and I a chance to get back to PR #72? He's traveling right now, but I think we could do this next week.

**Comment by emiliom** [comment]
@sreeder requested a review from @horsburgh too, so I won't go ahead and merge. Unless you want me to!

**Comment by horsburgh** [comment]
Just reviewed this with @sreeder. Looks good so I'm going to merge so she can create the new release.

**Comment by emiliom** [comment]
> Just reviewed this with @sreeder. Looks good so I'm going to merge so she can create the new release.

Great! But can you comment on [this comment/suggestion of mine](81#issuecomment-301962692), before issuing a new release?

> Regarding issuing a new release: given that a release was issued just less than two weeks ago, how about we wait a little longer to give @ocefpaf and I a chance to get back to PR #72? He's traveling right now, but I think we could do this next week.

**Comment by horsburgh** [comment]
@emiliom - we can wait, but not too long. This isn't really adding much new functionality, it's just removing a bunch of cruft.

**Comment by emiliom** [comment]
> This isn't really adding much new functionality, it's just removing a bunch of cruft.

@horsburgh , PR #72 also was removing cruft and not adding new functionality. @ocefpaf and I have now addressed it and merged it, so we're good to go.

@sreeder, go ahead and create a new release whenever you'd like.

**Comment by emiliom** [comment]
@sreeder, FYI, **if you have time** today to create the new odm2api release, @ocefpaf *likely* has time to then create the new conda and pypi packages late today. 

He's still traveling (in the US, on Eastern time), but allocated time today and part of tomorrow to work on our project. He was planning to work on the wofpy release today, but Don and I can't coordinate with him today, so a bit of slack probably opened up.

It's your call, though. No pressure! Just wanted to make you aware of that circumstance.

**Comment by sreeder** [comment]
@emiliom Thanks for the update!

**Pull request merged**
