### PR TITLE
Add Travis-CI badge

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR only adds the Travis-CI badge in the GitHub front page (README.md).
It should help us to keep track of the tests.

@sreeder it seems that AppVeyor is running on your account. Can you get the badge URL for us? I can add it in this PR too.

- go to  https://ci.appveyor.com/project/sreeder/odm2pythonapi `setting`
- `Badges`
- copy-and-paste the `Sample markdown code`

### CODE REVIEW

**Comment by sreeder** [comment]
@ocefpaf  I added the badge to your Readme file.

**Comment by ocefpaf** [comment]
Thanks @sreeder!

**Comment by emiliom** [comment]
@ocefpaf and @sreeder, is this ready to merge? It says that "All checks have failed", but the "branch has no conflicts with the base branch".

Just doing some house cleanups.

**Comment by ocefpaf** [comment]
The failures are unrelated to this PRs. In fact the addition of the bages is to draw attention to the failures that existed for a while now.

**Pull request merged**
