### PR TITLE
python 3.x compatibility 

### PR DESCRIPTION
**Pull request by miguelcleon**
Two changes for compatiability with python 3.x: 

print statements were changed to enclose the printed text in parenthesis. 

A similar/related changes to exceptions:

Where in python 2.x this was valid:

except Exception, e:

In python 3.x it needs to be: 
 
except Exception as e:

None of these should cause any functional changes.

### CODE REVIEW

**Comment by valentinedwv** [comment]
Looks good.

**Comment by Castronova** [comment]
I ran into a geoalchemy error when installing this PR using Python 3, see #59

**Comment by valentinedwv** [comment]
@miguelcleon can you enable a couple versions of python 3.0 in .travis.yml

**Comment by miguelcleon** [comment]
Looks like mysql-python also does not yet support Python 3.x 
It does build properly for Python 2.7, so this still works and are changes that will need to be made eventually. 
https://travis-ci.org/miguelcleon/ODM2PythonAPI/builds/124805005

**Pull request merged**
